language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t urmilla017/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true urmilla017/react-docker npm run test
