language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t urmilla017/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true urmilla017/react-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-docker"
  env: "Reactdocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-929218324785"
  bucket_path: "react-docker"
  on:
    branch: master
  access_ley_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
